In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('mawaid_saifiyah.csv')
data

,id,its_number,business_id,business_name,contact_name,phone_no,email_id,annual_turnover,gstn_no,fssai_no,brouchers,created_at,created_by,updated_at,updated_by,is_deleted
0,81,20320207,0,Al Maimoon Asal,Shk Jafferussadik Maimoon,9619595152,jsmaimoon@gmail.com,1 - 10 lacs,0,0,Products/26d0673e48543d04dda28c5781c5c92f.JPG,2018-04-12,NaN,NaN,NaN,0
1,79,20325546,5380,NaN,Mulla Shabbir bhai Zainuddin bhai Chikhaliwala,9823038016,shantapioca52@yahoo.com,1 Cr - 25 Cr,0,0,Products/7cf445596b808ad39ddee637a3604d9b.jpeg,2018-04-12,8337.0,NaN,NaN,0
2,51,20335835,0,K.M.Trading.Co,Saifuddin Gandhi,9898645252,stgandhi72@gmail.com,50 lacs - 1 Cr,0,0,Products/42a13629e1e5a71191270783295e662d.jpg,2018-04-11,NaN,NaN,NaN,0
3,82,20352092,0,Taherabad enterprises,Abbas Jamali,9558161452,qutubpalace@gmail.com,1 - 10 lacs,0,0,Products/4928866c8c2cee3c1b2bbf97756c7027.JPG,2018-04-12,NaN,NaN,NaN,0
4,22,20359211,0,Farsi,Farida,8758196652,Soni_2512@hotmail.com,1 - 10 lacs,0,0,Products/1ed8c6a1492c551f10c135c79f702429.jpg,2018-04-11,NaN,NaN,NaN,0
5,18,20397478,4736,NaN,Mulla Shabbir bhai Shaikh Hasan bhai Bhatia,919920761325,MD@SHBConsultant.Com,10 lacs - 50 lacs,0,0,Products/4669b6d219e5b0bc62249e4a72a7b707.png,2018-04-11,1097.0,NaN,NaN,0
6,53,20405595,0,Hasanji Masala,Shabbir Hussain Sabir,918839349125,sabir.mariya@gmail.com,1 - 10 lacs,0,0,Products/574ba0602591c1e896703c989a15b7d1.pdf,2018-04-11,NaN,NaN,NaN,0
7,63,20407156,0,Honesty Traders,TAHER,9486186110,honestytraders@yahoo.com,50 lacs - 1 Cr,0,0,Products/240f79418edf60e437ea2b9c64be2242.jpg,2018-04-12,NaN,NaN,NaN,0
8,71,20421962,0,Fakhri cororesan,Aliasger aarif bhai,9824299652,Alikapasi37@gmail.com,1 - 10 lacs,0,0,Products/9d9c7423e9d3eaa49f2c7b681f5b26b4.jpg,2018-04-12,NaN,NaN,NaN,0
9,33,20437633,4743,NaN,Yusuf Bhai bhatiya,919930012652,mustafa_yb52@hotmail.com,1 - 10 lacs,0,0,Products/d06afceada1d071a389208ac5a36bcd3.jpg,2018-04-11,18594.0,NaN,NaN,0
10,62,30302549,0,Arwacomputers,Sakina,7303457052,arwacomputers@gmail.com,1 - 10 lacs,0,0,Products/5a1790274d50da75aaeda5ba457accd7.png,2018-04-12,NaN,NaN,NaN,0
11,52,30305885,0,Babji supplier,Moiz,9152236805,Moizjumana1@gmail.com,1 - 10 lacs,0,0,Products/c9dd740997b88abefeefe29b1a3a748e.jpg,2018-04-11,NaN,NaN,NaN,0
12,47,30311818,0,Blue Star Food Products,Sevwala,9870007522,crownfoods@gmail.com,50 lacs - 1 Cr,27000000,115110020,Products/1f1293b7fee592396f5f49f2490c8216.jpg,2018-04-11,NaN,NaN,NaN,0
13,29,30314735,0,MN CREATIONS,Murtaza,9223213072,mncreations4u@gmail.com,10 lacs - 50 lacs,0,0,Products/a34436b007c80b911f120530b998c83c.jpg,2018-04-11,NaN,NaN,NaN,0
14,61,30321762,0,NutriEd,Arwa Motiwala,9460515458,arwamotiwala@yahoo.in,1 - 10 lacs,0,0,Products/7641c388229e8c8829f2ed74bfc98e7c.jpeg,2018-04-12,NaN,NaN,NaN,0
15,64,30328462,0,Diamond samosa shop,Burhanuddin,9833176862,bsamosawala110@gmail.com,1 - 10 lacs,0,0,Products/fa2385f53c57ad54a8011ff235e95d31.png,2018-04-12,NaN,NaN,NaN,0
16,28,30336381,0,AL-AQMAR TRADERS,Taher Baldiwala,8369015145,jamali.taher@gmail.com,1 - 10 lacs,0,0,Products/9876ae77ba230cfd4276b7e9b2ad9484.jpg,2018-04-11,NaN,NaN,NaN,0
17,65,30377845,0,Queens Bakery,Mustansir Lokhandwala,8602585698,abizarhakimji@gmail.com,1 - 10 lacs,0,0,Products/12497f8ef0ec0dfa16c1e891d6bd4332.jpg,2018-04-12,NaN,NaN,NaN,0
18,17,30378290,0,raj distributors,husain taskeen,9665278652,husain.taskeen53@gmail.com,1 - 10 lacs,279125,0,Products/a3d666c043e0f5256352969b98f034be.jpg,2018-04-11,NaN,NaN,NaN,0
19,44,30390067,0,Creative Food Catering,Abdulkadir Khandalawala,9049484325,abdul_227143@yahoo.com,10 lacs - 50 lacs,0,0,Products/5b1067c002ef78cb20a29d60a35e542d.jpeg,2018-04-11,NaN,NaN,NaN,0
20,32,30402809,0,Homemade Wadi Wholeseller,Jumana Jalgaonwala,9893643200,murtaza2410@gmail.com,1 - 10 lacs,0,0,Products/dd5bd18d397dfac8e1ebd4b940262b50.jpg,2018-04-11,NaN,NaN,NaN,0
21,76,30403422,0,Raj Traders,Abbasali Abdeali Sarangpurwala,73038308354,abbasali.s110@gmail.com,1 - 10 lacs,0,0,Products/30034dfbb0c1af8916f392757fbd47eb.jpeg,2018-04-12,NaN,NaN,NaN,0
22,24,30410156,0,Qusai Lifestyle Private Limited,Huzayfa,9321115152,huzayfaattar@gmail.com,1 - 10 lacs,0,1151600500,Products/7349fdbb1a0d362b0bab75122ef7c930.jpg,2018-04-11,NaN,NaN,NaN,0
23,48,30420950,0,Jaujabhoney,Ruqaiya taher topiwala,9636853385,ruk_saasa@yahoo.com,1 - 10 lacs,0,0,Products/a67db4a0eb00680394fa99dfb24034e0.jpg,2018-04-11,NaN,NaN,NaN,0
24,72,30435533,0,burhani imports and exports,taiyeb,8460296596,burhanimportexport@outlook.com,1 - 10 lacs,24,0,Products/f2cb048ece37d33aa04e203f057daac6.png,2018-04-12,NaN,NaN,NaN,0
25,39,30438194,0,GUJARAT AGRO FOOD PROCESSORS,Juzer Madarwala,9246577252,info@rasily.com,50 lacs - 1 Cr,0,0,Products/b2c16ed32ec8fad514e9ba7a230f3b2c.jpg,2018-04-11,NaN,NaN,NaN,0
26,55,30448903,1736,NaN,Abbas bhai Abdulghafoor bhai Gondal wala,9039309252,adiltraveltourism@gmail.com,1 - 10 lacs,0,0,Products/3894fc8934ef26722d7517dc6e749222.jpeg,2018-04-12,83.0,NaN,NaN,0
27,70,30474521,0,Haidery Food,Hussain Fakhari,9920095852,hussain_fakhari@yahoo.co.in,1 - 10 lacs,0,0,Products/5c051a388c023b6bd08aefb4a17989ea.jpg,2018-04-12,NaN,NaN,NaN,0
28,26,30477786,0,ALISTER EQUIPMENTS,MULLA SHABBIR FAKHRUDDIN MASTER,9823378666,sfmaster786@gmail.com,1 Cr - 25 Cr,0,0,Products/a381eb84df006a4a4ecb3ee538d5a9bb.pdf,2018-04-11,NaN,NaN,NaN,0
29,16,30494986,0,Vestige marketing,Huseina,7718029056,huseinabdalal@yahoo.co.in,1 - 10 lacs,0,0,Products/d55d97722bc0ad2e24ac07890ab3d3a5.jpg,2018-04-11,NaN,NaN,NaN,0
30,54,30495120,0,Little Honey,Taher Topiwala,006590178884,Tahertopi@gmail.com,10 lacs - 50 lacs,0,0,Products/29a56f210fef26aa9548f8257e162a84.png,2018-04-12,NaN,NaN,NaN,0
31,45,30802417,0,Muffadal Enterprise,Mohammed Gadyali,9666241995,Muffadalent@gmail.com,10 lacs - 50 lacs,0,0,Products/d541e70b225ce1ef01a148459e81a01a.pdf,2018-04-11,NaN,NaN,NaN,0
32,27,30909139,0,Raudat industries,Nisrin tailor,7357535288,nisrin.tara@gmail.com,1 - 10 lacs,0,0,Products/7453aab7bbff2293b2a77e8a467adaac.jpg,2018-04-11,NaN,NaN,NaN,0
33,19,30922537,0,Qasr Honey,Saleh and Mustafa Daginawala,0061411162892,qasrhoney@gmail.com,1 - 10 lacs,0,0,Products/e88d58688c1472b8e204c2fb638d77d0.jpg,2018-04-11,NaN,NaN,NaN,0
34,68,40401311,0,Shahi Raj,M Shabbir Abdulhusain Poonawala,7387095152,shabbir@abdeali.org,1 - 10 lacs,2781511,0,Products/00f7accd158564852d919e7e1847e361.jpg,2018-04-12,NaN,NaN,NaN,0
35,9,40454741,0,NaN,Abizer bhai Shabbirhusain bhai Madarwala,03366869257,abuzar_shabbir@hotmail.com,10 lacs - 50 lacs,0,0,Products/9f8f3c9b2e157bc895115d72e5117479.pdf,2018-04-06,16191.0,NaN,NaN,0
36,11,40459627,2909,NaN,Qasim,28189902342121231231231231231231231231231231,qasimshabbir@gmail.com,50 lacs - 1 Cr,0,0,Products/fca4b03a5b2a315f1feee4ec910a1f98.pdf,2018-04-06,4.0,NaN,NaN,0
37,67,40492326,0,Huzainskitchen,Zainab jamali,7066351446,Xainab52@gmail.com,1 - 10 lacs,0,0,Products/4f58d462a117e80cd1ce98c8ee5b22ec.jpg,2018-04-12,NaN,NaN,NaN,0
38,56,40497836,0,The little kitchen,Huzaifa mustafa,00923323591521,Lkco.khi@gmail.com,50 lacs - 1 Cr,0,0,Products/9abf7fa90e2bc04fafc7d5429eba0d00.jpg,2018-04-12,NaN,NaN,NaN,0
39,66,50426354,0,Choice corner,Juzer,7096115568,Ukanijuzer53@gmail.com,10 lacs - 50 lacs,0,0,Products/026d03627edb9744123c5306fbbbdf98.jpg,2018-04-12,NaN,NaN,NaN,0
40,25,50430949,0,ROYAL TAJMAHAL BEVERAGES,Husain Tajmahal,9909562552,husain.tajmahal128@gmail.com,50 lacs - 1 Cr,0,0,Products/db87381cb83d6a31f589f71f7885e01f.jpg,2018-04-11,NaN,NaN,NaN,0
41,50,50436202,0,Fiesta Bakers and Confectioners,Saifuddin Habibulla,9822059334,fiesta093@gmail.com,1 Cr - 25 Cr,0,0,Products/d838b9a95f754d74be545278bdcce14c.JPG,2018-04-11,NaN,NaN,NaN,0
42,43,50458658,0,World best health care product. Foreverliving ...,Mustafaa,8099707899,mus2212@gmail.com,100 Cr and Above,0,0,Products/0948eb3eaf134291699905b741f5cab4.pdf,2018-04-11,NaN,NaN,NaN,0
43,31,50462168,0,Roshan Pharma,Zakir Husain Kanchwala,7693976055,zakirkanchwala007@gmail.com,1 - 10 lacs,0,0,Products/3d9fa60c7127bccb5077464775a83cb1.jpg,2018-04-11,NaN,NaN,NaN,0
44,78,50476798,0,Vegetable supplier,Zoher abdeali siamwala,9374731392,Zohersiamwala1974@gmail @gmail.com,1 - 10 lacs,0,0,Products/c4643919a0cf842e1a1b45d8f8e315c9.jpg,2018-04-12,NaN,NaN,NaN,0
45,13,50494975,0,Al fakhri trading,Fatema nanabhai,254722604267,msfbj21@hotmail.com,1 - 10 lacs,0,0,Products/bad15c9d4aabad65e232a57844e196cc.jpg,2018-04-11,NaN,NaN,NaN,0
46,58,60408532,0,Vestige,Batul Aziz Vania,7383931934,batulvania36@gmail.com,1 - 10 lacs,0,0,Products/9b1cc173bae7954669102dc244955949.jpg,2018-04-12,NaN,NaN,NaN,0
47,30,60419607,0,CHEM IMPEX,Anis Patel,9408041433,mktg.chemimpex@gmail.com,1 Cr - 25 Cr,0,1071703126,Products/5d527bdf5546988cfc32eb7a57d6a363.pdf,2018-04-11,NaN,NaN,NaN,0
48,46,60445477,0,Pakeezah Paan Mouth-freshener,Husain,9490692461,mca.husain@gmail.com,1 - 10 lacs,0,0,Products/5bd0d25cbdda7c6a85ca097546afcb5f.jpg,2018-04-11,NaN,NaN,NaN,0
49,80,60464992,0,Taheri Traders,Taher Saifi,7725805253,saifitaher@gmail.com,1 - 10 lacs,0,0,Products/1f46f472f6c6fbfa512a368cec70eff6.JPG,2018-04-12,NaN,NaN,NaN,0

In [7]:
data.shape

(50, 16)

In [8]:
data.size

800

In [11]:
data.groupby(['its_number']).count()

,id,business_id,business_name,contact_name,phone_no,email_id,annual_turnover,gstn_no,fssai_no,brouchers,created_at,created_by,updated_at,updated_by,is_deleted
its_number,,,,,,,,,,,,,,,
20320207,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
20325546,1,1,0,1,1,1,1,1,1,1,1,1,0,0,1
20335835,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
20352092,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
20359211,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
20397478,1,1,0,1,1,1,1,1,1,1,1,1,0,0,1
20405595,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
20407156,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
20421962,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
20437633,1,1,0,1,1,1,1,1,1,1,1,1,0,0,1
30302549,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
30305885,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
30311818,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
30314735,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
30321762,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
30328462,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
30336381,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
30377845,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
30378290,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
30390067,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
30402809,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
30403422,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
30410156,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
30420950,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
30435533,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
30438194,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
30448903,1,1,0,1,1,1,1,1,1,1,1,1,0,0,1
30474521,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
30477786,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
30494986,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
30495120,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
30802417,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
30909139,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
30922537,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
40401311,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
40454741,1,1,0,1,1,1,1,1,1,1,1,1,0,0,1
40459627,1,1,0,1,1,1,1,1,1,1,1,1,0,0,1
40492326,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
40497836,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
50426354,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
50430949,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
50436202,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
50458658,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
50462168,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
50476798,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
50494975,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
60408532,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
60419607,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
60445477,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
60464992,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1

In [12]:
data.groupby(['business_name']).count()

,id,its_number,business_id,contact_name,phone_no,email_id,annual_turnover,gstn_no,fssai_no,brouchers,created_at,created_by,updated_at,updated_by,is_deleted
business_name,,,,,,,,,,,,,,,
AL-AQMAR TRADERS,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
ALISTER EQUIPMENTS,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Al Maimoon Asal,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Al fakhri trading,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Arwacomputers,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Babji supplier,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Blue Star Food Products,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
CHEM IMPEX,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Choice corner,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Creative Food Catering,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Diamond samosa shop,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Fakhri cororesan,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Farsi,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Fiesta Bakers and Confectioners,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
GUJARAT AGRO FOOD PROCESSORS,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Haidery Food,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Hasanji Masala,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Homemade Wadi Wholeseller,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Honesty Traders,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Huzainskitchen,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Jaujabhoney,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
K.M.Trading.Co,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Little Honey,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
MN CREATIONS,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Muffadal Enterprise,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
NutriEd,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Pakeezah Paan Mouth-freshener,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Qasr Honey,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Queens Bakery,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Qusai Lifestyle Private Limited,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
ROYAL TAJMAHAL BEVERAGES,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Raj Traders,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Raudat industries,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Roshan Pharma,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Shahi Raj,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Taherabad enterprises,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Taheri Traders,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
The little kitchen,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Vegetable supplier,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Vestige,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
Vestige marketing,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
World best health care product. Foreverliving inte,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
burhani imports and exports,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
raj distributors,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1

In [13]:
data.groupby(['annual_turnover']).count()

,id,its_number,business_id,business_name,contact_name,phone_no,email_id,gstn_no,fssai_no,brouchers,created_at,created_by,updated_at,updated_by,is_deleted
annual_turnover,,,,,,,,,,,,,,,
1 - 10 lacs,31,31,31,29,31,31,31,31,31,31,31,2,0,0,31
1 Cr - 25 Cr,4,4,4,3,4,4,4,4,4,4,4,1,0,0,4
10 lacs - 50 lacs,7,7,7,5,7,7,7,7,7,7,7,2,0,0,7
100 Cr and Above,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1
50 lacs - 1 Cr,7,7,7,6,7,7,7,7,7,7,7,1,0,0,7

In [17]:
lacs10 = (data.annual_turnover == '1 - 10 lacs')
print(lacs10)
print(sum(lacs10))

0      True
1     False
2     False
3      True
4      True
5     False
6      True
7     False
8      True
9      True
10     True
11     True
12    False
13    False
14     True
15     True
16     True
17     True
18     True
19    False
20     True
21     True
22     True
23     True
24     True
25    False
26     True
27     True
28    False
29     True
30    False
31    False
32     True
33     True
34     True
35    False
36    False
37     True
38    False
39    False
40    False
41    False
42    False
43     True
44     True
45     True
46     True
47    False
48     True
49     True
Name: annual_turnover, dtype: bool
31

In [18]:
data[lacs10]

,id,its_number,business_id,business_name,contact_name,phone_no,email_id,annual_turnover,gstn_no,fssai_no,brouchers,created_at,created_by,updated_at,updated_by,is_deleted
0,81,20320207,0,Al Maimoon Asal,Shk Jafferussadik Maimoon,9619595152,jsmaimoon@gmail.com,1 - 10 lacs,0,0,Products/26d0673e48543d04dda28c5781c5c92f.JPG,2018-04-12,NaN,NaN,NaN,0
3,82,20352092,0,Taherabad enterprises,Abbas Jamali,9558161452,qutubpalace@gmail.com,1 - 10 lacs,0,0,Products/4928866c8c2cee3c1b2bbf97756c7027.JPG,2018-04-12,NaN,NaN,NaN,0
4,22,20359211,0,Farsi,Farida,8758196652,Soni_2512@hotmail.com,1 - 10 lacs,0,0,Products/1ed8c6a1492c551f10c135c79f702429.jpg,2018-04-11,NaN,NaN,NaN,0
6,53,20405595,0,Hasanji Masala,Shabbir Hussain Sabir,918839349125,sabir.mariya@gmail.com,1 - 10 lacs,0,0,Products/574ba0602591c1e896703c989a15b7d1.pdf,2018-04-11,NaN,NaN,NaN,0
8,71,20421962,0,Fakhri cororesan,Aliasger aarif bhai,9824299652,Alikapasi37@gmail.com,1 - 10 lacs,0,0,Products/9d9c7423e9d3eaa49f2c7b681f5b26b4.jpg,2018-04-12,NaN,NaN,NaN,0
9,33,20437633,4743,NaN,Yusuf Bhai bhatiya,919930012652,mustafa_yb52@hotmail.com,1 - 10 lacs,0,0,Products/d06afceada1d071a389208ac5a36bcd3.jpg,2018-04-11,18594.0,NaN,NaN,0
10,62,30302549,0,Arwacomputers,Sakina,7303457052,arwacomputers@gmail.com,1 - 10 lacs,0,0,Products/5a1790274d50da75aaeda5ba457accd7.png,2018-04-12,NaN,NaN,NaN,0
11,52,30305885,0,Babji supplier,Moiz,9152236805,Moizjumana1@gmail.com,1 - 10 lacs,0,0,Products/c9dd740997b88abefeefe29b1a3a748e.jpg,2018-04-11,NaN,NaN,NaN,0
14,61,30321762,0,NutriEd,Arwa Motiwala,9460515458,arwamotiwala@yahoo.in,1 - 10 lacs,0,0,Products/7641c388229e8c8829f2ed74bfc98e7c.jpeg,2018-04-12,NaN,NaN,NaN,0
15,64,30328462,0,Diamond samosa shop,Burhanuddin,9833176862,bsamosawala110@gmail.com,1 - 10 lacs,0,0,Products/fa2385f53c57ad54a8011ff235e95d31.png,2018-04-12,NaN,NaN,NaN,0
16,28,30336381,0,AL-AQMAR TRADERS,Taher Baldiwala,8369015145,jamali.taher@gmail.com,1 - 10 lacs,0,0,Products/9876ae77ba230cfd4276b7e9b2ad9484.jpg,2018-04-11,NaN,NaN,NaN,0
17,65,30377845,0,Queens Bakery,Mustansir Lokhandwala,8602585698,abizarhakimji@gmail.com,1 - 10 lacs,0,0,Products/12497f8ef0ec0dfa16c1e891d6bd4332.jpg,2018-04-12,NaN,NaN,NaN,0
18,17,30378290,0,raj distributors,husain taskeen,9665278652,husain.taskeen53@gmail.com,1 - 10 lacs,279125,0,Products/a3d666c043e0f5256352969b98f034be.jpg,2018-04-11,NaN,NaN,NaN,0
20,32,30402809,0,Homemade Wadi Wholeseller,Jumana Jalgaonwala,9893643200,murtaza2410@gmail.com,1 - 10 lacs,0,0,Products/dd5bd18d397dfac8e1ebd4b940262b50.jpg,2018-04-11,NaN,NaN,NaN,0
21,76,30403422,0,Raj Traders,Abbasali Abdeali Sarangpurwala,73038308354,abbasali.s110@gmail.com,1 - 10 lacs,0,0,Products/30034dfbb0c1af8916f392757fbd47eb.jpeg,2018-04-12,NaN,NaN,NaN,0
22,24,30410156,0,Qusai Lifestyle Private Limited,Huzayfa,9321115152,huzayfaattar@gmail.com,1 - 10 lacs,0,1151600500,Products/7349fdbb1a0d362b0bab75122ef7c930.jpg,2018-04-11,NaN,NaN,NaN,0
23,48,30420950,0,Jaujabhoney,Ruqaiya taher topiwala,9636853385,ruk_saasa@yahoo.com,1 - 10 lacs,0,0,Products/a67db4a0eb00680394fa99dfb24034e0.jpg,2018-04-11,NaN,NaN,NaN,0
24,72,30435533,0,burhani imports and exports,taiyeb,8460296596,burhanimportexport@outlook.com,1 - 10 lacs,24,0,Products/f2cb048ece37d33aa04e203f057daac6.png,2018-04-12,NaN,NaN,NaN,0
26,55,30448903,1736,NaN,Abbas bhai Abdulghafoor bhai Gondal wala,9039309252,adiltraveltourism@gmail.com,1 - 10 lacs,0,0,Products/3894fc8934ef26722d7517dc6e749222.jpeg,2018-04-12,83.0,NaN,NaN,0
27,70,30474521,0,Haidery Food,Hussain Fakhari,9920095852,hussain_fakhari@yahoo.co.in,1 - 10 lacs,0,0,Products/5c051a388c023b6bd08aefb4a17989ea.jpg,2018-04-12,NaN,NaN,NaN,0
29,16,30494986,0,Vestige marketing,Huseina,7718029056,huseinabdalal@yahoo.co.in,1 - 10 lacs,0,0,Products/d55d97722bc0ad2e24ac07890ab3d3a5.jpg,2018-04-11,NaN,NaN,NaN,0
32,27,30909139,0,Raudat industries,Nisrin tailor,7357535288,nisrin.tara@gmail.com,1 - 10 lacs,0,0,Products/7453aab7bbff2293b2a77e8a467adaac.jpg,2018-04-11,NaN,NaN,NaN,0
33,19,30922537,0,Qasr Honey,Saleh and Mustafa Daginawala,0061411162892,qasrhoney@gmail.com,1 - 10 lacs,0,0,Products/e88d58688c1472b8e204c2fb638d77d0.jpg,2018-04-11,NaN,NaN,NaN,0
34,68,40401311,0,Shahi Raj,M Shabbir Abdulhusain Poonawala,7387095152,shabbir@abdeali.org,1 - 10 lacs,2781511,0,Products/00f7accd158564852d919e7e1847e361.jpg,2018-04-12,NaN,NaN,NaN,0
37,67,40492326,0,Huzainskitchen,Zainab jamali,7066351446,Xainab52@gmail.com,1 - 10 lacs,0,0,Products/4f58d462a117e80cd1ce98c8ee5b22ec.jpg,2018-04-12,NaN,NaN,NaN,0
43,31,50462168,0,Roshan Pharma,Zakir Husain Kanchwala,7693976055,zakirkanchwala007@gmail.com,1 - 10 lacs,0,0,Products/3d9fa60c7127bccb5077464775a83cb1.jpg,2018-04-11,NaN,NaN,NaN,0
44,78,50476798,0,Vegetable supplier,Zoher abdeali siamwala,9374731392,Zohersiamwala1974@gmail @gmail.com,1 - 10 lacs,0,0,Products/c4643919a0cf842e1a1b45d8f8e315c9.jpg,2018-04-12,NaN,NaN,NaN,0
45,13,50494975,0,Al fakhri trading,Fatema nanabhai,254722604267,msfbj21@hotmail.com,1 - 10 lacs,0,0,Products/bad15c9d4aabad65e232a57844e196cc.jpg,2018-04-11,NaN,NaN,NaN,0
46,58,60408532,0,Vestige,Batul Aziz Vania,7383931934,batulvania36@gmail.com,1 - 10 lacs,0,0,Products/9b1cc173bae7954669102dc244955949.jpg,2018-04-12,NaN,NaN,NaN,0
48,46,60445477,0,Pakeezah Paan Mouth-freshener,Husain,9490692461,mca.husain@gmail.com,1 - 10 lacs,0,0,Products/5bd0d25cbdda7c6a85ca097546afcb5f.jpg,2018-04-11,NaN,NaN,NaN,0
49,80,60464992,0,Taheri Traders,Taher Saifi,7725805253,saifitaher@gmail.com,1 - 10 lacs,0,0,Products/1f46f472f6c6fbfa512a368cec70eff6.JPG,2018-04-12,NaN,NaN,NaN,0

In [32]:
data[(data.gstn_no != 0) & (data.annual_turnover == '1 - 10 lacs')]

,id,its_number,business_id,business_name,contact_name,phone_no,email_id,annual_turnover,gstn_no,fssai_no,brouchers,created_at,created_by,updated_at,updated_by,is_deleted
18,17,30378290,0,raj distributors,husain taskeen,9665278652,husain.taskeen53@gmail.com,1 - 10 lacs,279125,0,Products/a3d666c043e0f5256352969b98f034be.jpg,2018-04-11,NaN,NaN,NaN,0
24,72,30435533,0,burhani imports and exports,taiyeb,8460296596,burhanimportexport@outlook.com,1 - 10 lacs,24,0,Products/f2cb048ece37d33aa04e203f057daac6.png,2018-04-12,NaN,NaN,NaN,0
34,68,40401311,0,Shahi Raj,M Shabbir Abdulhusain Poonawala,7387095152,shabbir@abdeali.org,1 - 10 lacs,2781511,0,Products/00f7accd158564852d919e7e1847e361.jpg,2018-04-12,NaN,NaN,NaN,0

In [37]:
data[(data.contact_name.str.startswith('S')) & (data.annual_turnover == '1 - 10 lacs')]

,id,its_number,business_id,business_name,contact_name,phone_no,email_id,annual_turnover,gstn_no,fssai_no,brouchers,created_at,created_by,updated_at,updated_by,is_deleted
0,81,20320207,0,Al Maimoon Asal,Shk Jafferussadik Maimoon,9619595152,jsmaimoon@gmail.com,1 - 10 lacs,0,0,Products/26d0673e48543d04dda28c5781c5c92f.JPG,2018-04-12,NaN,NaN,NaN,0
6,53,20405595,0,Hasanji Masala,Shabbir Hussain Sabir,918839349125,sabir.mariya@gmail.com,1 - 10 lacs,0,0,Products/574ba0602591c1e896703c989a15b7d1.pdf,2018-04-11,NaN,NaN,NaN,0
10,62,30302549,0,Arwacomputers,Sakina,7303457052,arwacomputers@gmail.com,1 - 10 lacs,0,0,Products/5a1790274d50da75aaeda5ba457accd7.png,2018-04-12,NaN,NaN,NaN,0
33,19,30922537,0,Qasr Honey,Saleh and Mustafa Daginawala,0061411162892,qasrhoney@gmail.com,1 - 10 lacs,0,0,Products/e88d58688c1472b8e204c2fb638d77d0.jpg,2018-04-11,NaN,NaN,NaN,0

In [38]:
data[(data.contact_name.str.startswith('A') & (data.annual_turnover.str.startswith('10')))]

,id,its_number,business_id,business_name,contact_name,phone_no,email_id,annual_turnover,gstn_no,fssai_no,brouchers,created_at,created_by,updated_at,updated_by,is_deleted
19,44,30390067,0,Creative Food Catering,Abdulkadir Khandalawala,9049484325,abdul_227143@yahoo.com,10 lacs - 50 lacs,0,0,Products/5b1067c002ef78cb20a29d60a35e542d.jpeg,2018-04-11,NaN,NaN,NaN,0
35,9,40454741,0,NaN,Abizer bhai Shabbirhusain bhai Madarwala,03366869257,abuzar_shabbir@hotmail.com,10 lacs - 50 lacs,0,0,Products/9f8f3c9b2e157bc895115d72e5117479.pdf,2018-04-06,16191.0,NaN,NaN,0

In [40]:
data.its_number[3:5]

3    20352092
4    20359211
Name: its_number, dtype: int64

In [41]:
data.loc[:, "its_number":"contact_name"]

,its_number,business_id,business_name,contact_name
0,20320207,0,Al Maimoon Asal,Shk Jafferussadik Maimoon
1,20325546,5380,NaN,Mulla Shabbir bhai Zainuddin bhai Chikhaliwala
2,20335835,0,K.M.Trading.Co,Saifuddin Gandhi
3,20352092,0,Taherabad enterprises,Abbas Jamali
4,20359211,0,Farsi,Farida
5,20397478,4736,NaN,Mulla Shabbir bhai Shaikh Hasan bhai Bhatia
6,20405595,0,Hasanji Masala,Shabbir Hussain Sabir
7,20407156,0,Honesty Traders,TAHER
8,20421962,0,Fakhri cororesan,Aliasger aarif bhai
9,20437633,4743,NaN,Yusuf Bhai bhatiya
10,30302549,0,Arwacomputers,Sakina
11,30305885,0,Babji supplier,Moiz
12,30311818,0,Blue Star Food Products,Sevwala
13,30314735,0,MN CREATIONS,Murtaza
14,30321762,0,NutriEd,Arwa Motiwala
15,30328462,0,Diamond samosa shop,Burhanuddin
16,30336381,0,AL-AQMAR TRADERS,Taher Baldiwala
17,30377845,0,Queens Bakery,Mustansir Lokhandwala
18,30378290,0,raj distributors,husain taskeen
19,30390067,0,Creative Food Catering,Abdulkadir Khandalawala
20,30402809,0,Homemade Wadi Wholeseller,Jumana Jalgaonwala
21,30403422,0,Raj Traders,Abbasali Abdeali Sarangpurwala
22,30410156,0,Qusai Lifestyle Private Limited,Huzayfa
23,30420950,0,Jaujabhoney,Ruqaiya taher topiwala
24,30435533,0,burhani imports and exports,taiyeb
25,30438194,0,GUJARAT AGRO FOOD PROCESSORS,Juzer Madarwala
26,30448903,1736,NaN,Abbas bhai Abdulghafoor bhai Gondal wala
27,30474521,0,Haidery Food,Hussain Fakhari
28,30477786,0,ALISTER EQUIPMENTS,MULLA SHABBIR FAKHRUDDIN MASTER
29,30494986,0,Vestige marketing,Huseina
30,30495120,0,Little Honey,Taher Topiwala
31,30802417,0,Muffadal Enterprise,Mohammed Gadyali
32,30909139,0,Raudat industries,Nisrin tailor
33,30922537,0,Qasr Honey,Saleh and Mustafa Daginawala
34,40401311,0,Shahi Raj,M Shabbir Abdulhusain Poonawala
35,40454741,0,NaN,Abizer bhai Shabbirhusain bhai Madarwala
36,40459627,2909,NaN,Qasim
37,40492326,0,Huzainskitchen,Zainab jamali
38,40497836,0,The little kitchen,Huzaifa mustafa
39,50426354,0,Choice corner,Juzer
40,50430949,0,ROYAL TAJMAHAL BEVERAGES,Husain Tajmahal
41,50436202,0,Fiesta Bakers and Confectioners,Saifuddin Habibulla
42,50458658,0,World best health care product. Foreverliving ...,Mustafaa
43,50462168,0,Roshan Pharma,Zakir Husain Kanchwala
44,50476798,0,Vegetable supplier,Zoher abdeali siamwala
45,50494975,0,Al fakhri trading,Fatema nanabhai
46,60408532,0,Vestige,Batul Aziz Vania
47,60419607,0,CHEM IMPEX,Anis Patel
48,60445477,0,Pakeezah Paan Mouth-freshener,Husain
49,60464992,0,Taheri Traders,Taher Saifi

In [42]:
del data['updated_at']
data.head()

,id,its_number,business_id,business_name,contact_name,phone_no,email_id,annual_turnover,gstn_no,fssai_no,brouchers,created_at,created_by,updated_by,is_deleted
0,81,20320207,0,Al Maimoon Asal,Shk Jafferussadik Maimoon,9619595152,jsmaimoon@gmail.com,1 - 10 lacs,0,0,Products/26d0673e48543d04dda28c5781c5c92f.JPG,2018-04-12,NaN,NaN,0
1,79,20325546,5380,NaN,Mulla Shabbir bhai Zainuddin bhai Chikhaliwala,9823038016,shantapioca52@yahoo.com,1 Cr - 25 Cr,0,0,Products/7cf445596b808ad39ddee637a3604d9b.jpeg,2018-04-12,8337.0,NaN,0
2,51,20335835,0,K.M.Trading.Co,Saifuddin Gandhi,9898645252,stgandhi72@gmail.com,50 lacs - 1 Cr,0,0,Products/42a13629e1e5a71191270783295e662d.jpg,2018-04-11,NaN,NaN,0
3,82,20352092,0,Taherabad enterprises,Abbas Jamali,9558161452,qutubpalace@gmail.com,1 - 10 lacs,0,0,Products/4928866c8c2cee3c1b2bbf97756c7027.JPG,2018-04-12,NaN,NaN,0
4,22,20359211,0,Farsi,Farida,8758196652,Soni_2512@hotmail.com,1 - 10 lacs,0,0,Products/1ed8c6a1492c551f10c135c79f702429.jpg,2018-04-11,NaN,NaN,0

In [43]:
data.iloc[0:3, 0:5]

,id,its_number,business_id,business_name,contact_name
0,81,20320207,0,Al Maimoon Asal,Shk Jafferussadik Maimoon
1,79,20325546,5380,NaN,Mulla Shabbir bhai Zainuddin bhai Chikhaliwala
2,51,20335835,0,K.M.Trading.Co,Saifuddin Gandhi

In [44]:
data2 = data.copy()

In [52]:
data2.iloc[0:3, 2] = 'NaN'
data2

,id,its_number,business_id,business_name,contact_name,phone_no,email_id,annual_turnover,gstn_no,fssai_no,brouchers,created_at,created_by,updated_by,is_deleted
0,81,20320207,NaN,Al Maimoon Asal,Shk Jafferussadik Maimoon,9619595152,jsmaimoon@gmail.com,1 - 10 lacs,0,0,Products/26d0673e48543d04dda28c5781c5c92f.JPG,2018-04-12,NaN,NaN,0
1,79,20325546,NaN,NaN,Mulla Shabbir bhai Zainuddin bhai Chikhaliwala,9823038016,shantapioca52@yahoo.com,1 Cr - 25 Cr,0,0,Products/7cf445596b808ad39ddee637a3604d9b.jpeg,2018-04-12,8337.0,NaN,0
2,51,20335835,NaN,K.M.Trading.Co,Saifuddin Gandhi,9898645252,stgandhi72@gmail.com,50 lacs - 1 Cr,0,0,Products/42a13629e1e5a71191270783295e662d.jpg,2018-04-11,NaN,NaN,0
3,82,20352092,0,Taherabad enterprises,Abbas Jamali,9558161452,qutubpalace@gmail.com,1 - 10 lacs,0,0,Products/4928866c8c2cee3c1b2bbf97756c7027.JPG,2018-04-12,NaN,NaN,0
4,22,20359211,0,Farsi,Farida,8758196652,Soni_2512@hotmail.com,1 - 10 lacs,0,0,Products/1ed8c6a1492c551f10c135c79f702429.jpg,2018-04-11,NaN,NaN,0
5,18,20397478,4736,NaN,Mulla Shabbir bhai Shaikh Hasan bhai Bhatia,919920761325,MD@SHBConsultant.Com,10 lacs - 50 lacs,0,0,Products/4669b6d219e5b0bc62249e4a72a7b707.png,2018-04-11,1097.0,NaN,0
6,53,20405595,0,Hasanji Masala,Shabbir Hussain Sabir,918839349125,sabir.mariya@gmail.com,1 - 10 lacs,0,0,Products/574ba0602591c1e896703c989a15b7d1.pdf,2018-04-11,NaN,NaN,0
7,63,20407156,0,Honesty Traders,TAHER,9486186110,honestytraders@yahoo.com,50 lacs - 1 Cr,0,0,Products/240f79418edf60e437ea2b9c64be2242.jpg,2018-04-12,NaN,NaN,0
8,71,20421962,0,Fakhri cororesan,Aliasger aarif bhai,9824299652,Alikapasi37@gmail.com,1 - 10 lacs,0,0,Products/9d9c7423e9d3eaa49f2c7b681f5b26b4.jpg,2018-04-12,NaN,NaN,0
9,33,20437633,4743,NaN,Yusuf Bhai bhatiya,919930012652,mustafa_yb52@hotmail.com,1 - 10 lacs,0,0,Products/d06afceada1d071a389208ac5a36bcd3.jpg,2018-04-11,18594.0,NaN,0
10,62,30302549,0,Arwacomputers,Sakina,7303457052,arwacomputers@gmail.com,1 - 10 lacs,0,0,Products/5a1790274d50da75aaeda5ba457accd7.png,2018-04-12,NaN,NaN,0
11,52,30305885,0,Babji supplier,Moiz,9152236805,Moizjumana1@gmail.com,1 - 10 lacs,0,0,Products/c9dd740997b88abefeefe29b1a3a748e.jpg,2018-04-11,NaN,NaN,0
12,47,30311818,0,Blue Star Food Products,Sevwala,9870007522,crownfoods@gmail.com,50 lacs - 1 Cr,27000000,115110020,Products/1f1293b7fee592396f5f49f2490c8216.jpg,2018-04-11,NaN,NaN,0
13,29,30314735,0,MN CREATIONS,Murtaza,9223213072,mncreations4u@gmail.com,10 lacs - 50 lacs,0,0,Products/a34436b007c80b911f120530b998c83c.jpg,2018-04-11,NaN,NaN,0
14,61,30321762,0,NutriEd,Arwa Motiwala,9460515458,arwamotiwala@yahoo.in,1 - 10 lacs,0,0,Products/7641c388229e8c8829f2ed74bfc98e7c.jpeg,2018-04-12,NaN,NaN,0
15,64,30328462,0,Diamond samosa shop,Burhanuddin,9833176862,bsamosawala110@gmail.com,1 - 10 lacs,0,0,Products/fa2385f53c57ad54a8011ff235e95d31.png,2018-04-12,NaN,NaN,0
16,28,30336381,0,AL-AQMAR TRADERS,Taher Baldiwala,8369015145,jamali.taher@gmail.com,1 - 10 lacs,0,0,Products/9876ae77ba230cfd4276b7e9b2ad9484.jpg,2018-04-11,NaN,NaN,0
17,65,30377845,0,Queens Bakery,Mustansir Lokhandwala,8602585698,abizarhakimji@gmail.com,1 - 10 lacs,0,0,Products/12497f8ef0ec0dfa16c1e891d6bd4332.jpg,2018-04-12,NaN,NaN,0
18,17,30378290,0,raj distributors,husain taskeen,9665278652,husain.taskeen53@gmail.com,1 - 10 lacs,279125,0,Products/a3d666c043e0f5256352969b98f034be.jpg,2018-04-11,NaN,NaN,0
19,44,30390067,0,Creative Food Catering,Abdulkadir Khandalawala,9049484325,abdul_227143@yahoo.com,10 lacs - 50 lacs,0,0,Products/5b1067c002ef78cb20a29d60a35e542d.jpeg,2018-04-11,NaN,NaN,0
20,32,30402809,0,Homemade Wadi Wholeseller,Jumana Jalgaonwala,9893643200,murtaza2410@gmail.com,1 - 10 lacs,0,0,Products/dd5bd18d397dfac8e1ebd4b940262b50.jpg,2018-04-11,NaN,NaN,0
21,76,30403422,0,Raj Traders,Abbasali Abdeali Sarangpurwala,73038308354,abbasali.s110@gmail.com,1 - 10 lacs,0,0,Products/30034dfbb0c1af8916f392757fbd47eb.jpeg,2018-04-12,NaN,NaN,0
22,24,30410156,0,Qusai Lifestyle Private Limited,Huzayfa,9321115152,huzayfaattar@gmail.com,1 - 10 lacs,0,1151600500,Products/7349fdbb1a0d362b0bab75122ef7c930.jpg,2018-04-11,NaN,NaN,0
23,48,30420950,0,Jaujabhoney,Ruqaiya taher topiwala,9636853385,ruk_saasa@yahoo.com,1 - 10 lacs,0,0,Products/a67db4a0eb00680394fa99dfb24034e0.jpg,2018-04-11,NaN,NaN,0
24,72,30435533,0,burhani imports and exports,taiyeb,8460296596,burhanimportexport@outlook.com,1 - 10 lacs,24,0,Products/f2cb048ece37d33aa04e203f057daac6.png,2018-04-12,NaN,NaN,0
25,39,30438194,0,GUJARAT AGRO FOOD PROCESSORS,Juzer Madarwala,9246577252,info@rasily.com,50 lacs - 1 Cr,0,0,Products/b2c16ed32ec8fad514e9ba7a230f3b2c.jpg,2018-04-11,NaN,NaN,0
26,55,30448903,1736,NaN,Abbas bhai Abdulghafoor bhai Gondal wala,9039309252,adiltraveltourism@gmail.com,1 - 10 lacs,0,0,Products/3894fc8934ef26722d7517dc6e749222.jpeg,2018-04-12,83.0,NaN,0
27,70,30474521,0,Haidery Food,Hussain Fakhari,9920095852,hussain_fakhari@yahoo.co.in,1 - 10 lacs,0,0,Products/5c051a388c023b6bd08aefb4a17989ea.jpg,2018-04-12,NaN,NaN,0
28,26,30477786,0,ALISTER EQUIPMENTS,MULLA SHABBIR FAKHRUDDIN MASTER,9823378666,sfmaster786@gmail.com,1 Cr - 25 Cr,0,0,Products/a381eb84df006a4a4ecb3ee538d5a9bb.pdf,2018-04-11,NaN,NaN,0
29,16,30494986,0,Vestige marketing,Huseina,7718029056,huseinabdalal@yahoo.co.in,1 - 10 lacs,0,0,Products/d55d97722bc0ad2e24ac07890ab3d3a5.jpg,2018-04-11,NaN,NaN,0
30,54,30495120,0,Little Honey,Taher Topiwala,006590178884,Tahertopi@gmail.com,10 lacs - 50 lacs,0,0,Products/29a56f210fef26aa9548f8257e162a84.png,2018-04-12,NaN,NaN,0
31,45,30802417,0,Muffadal Enterprise,Mohammed Gadyali,9666241995,Muffadalent@gmail.com,10 lacs - 50 lacs,0,0,Products/d541e70b225ce1ef01a148459e81a01a.pdf,2018-04-11,NaN,NaN,0
32,27,30909139,0,Raudat industries,Nisrin tailor,7357535288,nisrin.tara@gmail.com,1 - 10 lacs,0,0,Products/7453aab7bbff2293b2a77e8a467adaac.jpg,2018-04-11,NaN,NaN,0
33,19,30922537,0,Qasr Honey,Saleh and Mustafa Daginawala,0061411162892,qasrhoney@gmail.com,1 - 10 lacs,0,0,Products/e88d58688c1472b8e204c2fb638d77d0.jpg,2018-04-11,NaN,NaN,0
34,68,40401311,0,Shahi Raj,M Shabbir Abdulhusain Poonawala,7387095152,shabbir@abdeali.org,1 - 10 lacs,2781511,0,Products/00f7accd158564852d919e7e1847e361.jpg,2018-04-12,NaN,NaN,0
35,9,40454741,0,NaN,Abizer bhai Shabbirhusain bhai Madarwala,03366869257,abuzar_shabbir@hotmail.com,10 lacs - 50 lacs,0,0,Products/9f8f3c9b2e157bc895115d72e5117479.pdf,2018-04-06,16191.0,NaN,0
36,11,40459627,2909,NaN,Qasim,28189902342121231231231231231231231231231231,qasimshabbir@gmail.com,50 lacs - 1 Cr,0,0,Products/fca4b03a5b2a315f1feee4ec910a1f98.pdf,2018-04-06,4.0,NaN,0
37,67,40492326,0,Huzainskitchen,Zainab jamali,7066351446,Xainab52@gmail.com,1 - 10 lacs,0,0,Products/4f58d462a117e80cd1ce98c8ee5b22ec.jpg,2018-04-12,NaN,NaN,0
38,56,40497836,0,The little kitchen,Huzaifa mustafa,00923323591521,Lkco.khi@gmail.com,50 lacs - 1 Cr,0,0,Products/9abf7fa90e2bc04fafc7d5429eba0d00.jpg,2018-04-12,NaN,NaN,0
39,66,50426354,0,Choice corner,Juzer,7096115568,Ukanijuzer53@gmail.com,10 lacs - 50 lacs,0,0,Products/026d03627edb9744123c5306fbbbdf98.jpg,2018-04-12,NaN,NaN,0
40,25,50430949,0,ROYAL TAJMAHAL BEVERAGES,Husain Tajmahal,9909562552,husain.tajmahal128@gmail.com,50 lacs - 1 Cr,0,0,Products/db87381cb83d6a31f589f71f7885e01f.jpg,2018-04-11,NaN,NaN,0
41,50,50436202,0,Fiesta Bakers and Confectioners,Saifuddin Habibulla,9822059334,fiesta093@gmail.com,1 Cr - 25 Cr,0,0,Products/d838b9a95f754d74be545278bdcce14c.JPG,2018-04-11,NaN,NaN,0
42,43,50458658,0,World best health care product. Foreverliving ...,Mustafaa,8099707899,mus2212@gmail.com,100 Cr and Above,0,0,Products/0948eb3eaf134291699905b741f5cab4.pdf,2018-04-11,NaN,NaN,0
43,31,50462168,0,Roshan Pharma,Zakir Husain Kanchwala,7693976055,zakirkanchwala007@gmail.com,1 - 10 lacs,0,0,Products/3d9fa60c7127bccb5077464775a83cb1.jpg,2018-04-11,NaN,NaN,0
44,78,50476798,0,Vegetable supplier,Zoher abdeali siamwala,9374731392,Zohersiamwala1974@gmail @gmail.com,1 - 10 lacs,0,0,Products/c4643919a0cf842e1a1b45d8f8e315c9.jpg,2018-04-12,NaN,NaN,0
45,13,50494975,0,Al fakhri trading,Fatema nanabhai,254722604267,msfbj21@hotmail.com,1 - 10 lacs,0,0,Products/bad15c9d4aabad65e232a57844e196cc.jpg,2018-04-11,NaN,NaN,0
46,58,60408532,0,Vestige,Batul Aziz Vania,7383931934,batulvania36@gmail.com,1 - 10 lacs,0,0,Products/9b1cc173bae7954669102dc244955949.jpg,2018-04-12,NaN,NaN,0
47,30,60419607,0,CHEM IMPEX,Anis Patel,9408041433,mktg.chemimpex@gmail.com,1 Cr - 25 Cr,0,1071703126,Products/5d527bdf5546988cfc32eb7a57d6a363.pdf,2018-04-11,NaN,NaN,0
48,46,60445477,0,Pakeezah Paan Mouth-freshener,Husain,9490692461,mca.husain@gmail.com,1 - 10 lacs,0,0,Products/5bd0d25cbdda7c6a85ca097546afcb5f.jpg,2018-04-11,NaN,NaN,0
49,80,60464992,0,Taheri Traders,Taher Saifi,7725805253,saifitaher@gmail.com,1 - 10 lacs,0,0,Products/1f46f472f6c6fbfa512a368cec70eff6.JPG,2018-04-12,NaN,NaN,0

In [53]:
data2.dropna(how = 'any')
data2

,id,its_number,business_id,business_name,contact_name,phone_no,email_id,annual_turnover,gstn_no,fssai_no,brouchers,created_at,created_by,updated_by,is_deleted
0,81,20320207,NaN,Al Maimoon Asal,Shk Jafferussadik Maimoon,9619595152,jsmaimoon@gmail.com,1 - 10 lacs,0,0,Products/26d0673e48543d04dda28c5781c5c92f.JPG,2018-04-12,NaN,NaN,0
1,79,20325546,NaN,NaN,Mulla Shabbir bhai Zainuddin bhai Chikhaliwala,9823038016,shantapioca52@yahoo.com,1 Cr - 25 Cr,0,0,Products/7cf445596b808ad39ddee637a3604d9b.jpeg,2018-04-12,8337.0,NaN,0
2,51,20335835,NaN,K.M.Trading.Co,Saifuddin Gandhi,9898645252,stgandhi72@gmail.com,50 lacs - 1 Cr,0,0,Products/42a13629e1e5a71191270783295e662d.jpg,2018-04-11,NaN,NaN,0
3,82,20352092,0,Taherabad enterprises,Abbas Jamali,9558161452,qutubpalace@gmail.com,1 - 10 lacs,0,0,Products/4928866c8c2cee3c1b2bbf97756c7027.JPG,2018-04-12,NaN,NaN,0
4,22,20359211,0,Farsi,Farida,8758196652,Soni_2512@hotmail.com,1 - 10 lacs,0,0,Products/1ed8c6a1492c551f10c135c79f702429.jpg,2018-04-11,NaN,NaN,0
5,18,20397478,4736,NaN,Mulla Shabbir bhai Shaikh Hasan bhai Bhatia,919920761325,MD@SHBConsultant.Com,10 lacs - 50 lacs,0,0,Products/4669b6d219e5b0bc62249e4a72a7b707.png,2018-04-11,1097.0,NaN,0
6,53,20405595,0,Hasanji Masala,Shabbir Hussain Sabir,918839349125,sabir.mariya@gmail.com,1 - 10 lacs,0,0,Products/574ba0602591c1e896703c989a15b7d1.pdf,2018-04-11,NaN,NaN,0
7,63,20407156,0,Honesty Traders,TAHER,9486186110,honestytraders@yahoo.com,50 lacs - 1 Cr,0,0,Products/240f79418edf60e437ea2b9c64be2242.jpg,2018-04-12,NaN,NaN,0
8,71,20421962,0,Fakhri cororesan,Aliasger aarif bhai,9824299652,Alikapasi37@gmail.com,1 - 10 lacs,0,0,Products/9d9c7423e9d3eaa49f2c7b681f5b26b4.jpg,2018-04-12,NaN,NaN,0
9,33,20437633,4743,NaN,Yusuf Bhai bhatiya,919930012652,mustafa_yb52@hotmail.com,1 - 10 lacs,0,0,Products/d06afceada1d071a389208ac5a36bcd3.jpg,2018-04-11,18594.0,NaN,0
10,62,30302549,0,Arwacomputers,Sakina,7303457052,arwacomputers@gmail.com,1 - 10 lacs,0,0,Products/5a1790274d50da75aaeda5ba457accd7.png,2018-04-12,NaN,NaN,0
11,52,30305885,0,Babji supplier,Moiz,9152236805,Moizjumana1@gmail.com,1 - 10 lacs,0,0,Products/c9dd740997b88abefeefe29b1a3a748e.jpg,2018-04-11,NaN,NaN,0
12,47,30311818,0,Blue Star Food Products,Sevwala,9870007522,crownfoods@gmail.com,50 lacs - 1 Cr,27000000,115110020,Products/1f1293b7fee592396f5f49f2490c8216.jpg,2018-04-11,NaN,NaN,0
13,29,30314735,0,MN CREATIONS,Murtaza,9223213072,mncreations4u@gmail.com,10 lacs - 50 lacs,0,0,Products/a34436b007c80b911f120530b998c83c.jpg,2018-04-11,NaN,NaN,0
14,61,30321762,0,NutriEd,Arwa Motiwala,9460515458,arwamotiwala@yahoo.in,1 - 10 lacs,0,0,Products/7641c388229e8c8829f2ed74bfc98e7c.jpeg,2018-04-12,NaN,NaN,0
15,64,30328462,0,Diamond samosa shop,Burhanuddin,9833176862,bsamosawala110@gmail.com,1 - 10 lacs,0,0,Products/fa2385f53c57ad54a8011ff235e95d31.png,2018-04-12,NaN,NaN,0
16,28,30336381,0,AL-AQMAR TRADERS,Taher Baldiwala,8369015145,jamali.taher@gmail.com,1 - 10 lacs,0,0,Products/9876ae77ba230cfd4276b7e9b2ad9484.jpg,2018-04-11,NaN,NaN,0
17,65,30377845,0,Queens Bakery,Mustansir Lokhandwala,8602585698,abizarhakimji@gmail.com,1 - 10 lacs,0,0,Products/12497f8ef0ec0dfa16c1e891d6bd4332.jpg,2018-04-12,NaN,NaN,0
18,17,30378290,0,raj distributors,husain taskeen,9665278652,husain.taskeen53@gmail.com,1 - 10 lacs,279125,0,Products/a3d666c043e0f5256352969b98f034be.jpg,2018-04-11,NaN,NaN,0
19,44,30390067,0,Creative Food Catering,Abdulkadir Khandalawala,9049484325,abdul_227143@yahoo.com,10 lacs - 50 lacs,0,0,Products/5b1067c002ef78cb20a29d60a35e542d.jpeg,2018-04-11,NaN,NaN,0
20,32,30402809,0,Homemade Wadi Wholeseller,Jumana Jalgaonwala,9893643200,murtaza2410@gmail.com,1 - 10 lacs,0,0,Products/dd5bd18d397dfac8e1ebd4b940262b50.jpg,2018-04-11,NaN,NaN,0
21,76,30403422,0,Raj Traders,Abbasali Abdeali Sarangpurwala,73038308354,abbasali.s110@gmail.com,1 - 10 lacs,0,0,Products/30034dfbb0c1af8916f392757fbd47eb.jpeg,2018-04-12,NaN,NaN,0
22,24,30410156,0,Qusai Lifestyle Private Limited,Huzayfa,9321115152,huzayfaattar@gmail.com,1 - 10 lacs,0,1151600500,Products/7349fdbb1a0d362b0bab75122ef7c930.jpg,2018-04-11,NaN,NaN,0
23,48,30420950,0,Jaujabhoney,Ruqaiya taher topiwala,9636853385,ruk_saasa@yahoo.com,1 - 10 lacs,0,0,Products/a67db4a0eb00680394fa99dfb24034e0.jpg,2018-04-11,NaN,NaN,0
24,72,30435533,0,burhani imports and exports,taiyeb,8460296596,burhanimportexport@outlook.com,1 - 10 lacs,24,0,Products/f2cb048ece37d33aa04e203f057daac6.png,2018-04-12,NaN,NaN,0
25,39,30438194,0,GUJARAT AGRO FOOD PROCESSORS,Juzer Madarwala,9246577252,info@rasily.com,50 lacs - 1 Cr,0,0,Products/b2c16ed32ec8fad514e9ba7a230f3b2c.jpg,2018-04-11,NaN,NaN,0
26,55,30448903,1736,NaN,Abbas bhai Abdulghafoor bhai Gondal wala,9039309252,adiltraveltourism@gmail.com,1 - 10 lacs,0,0,Products/3894fc8934ef26722d7517dc6e749222.jpeg,2018-04-12,83.0,NaN,0
27,70,30474521,0,Haidery Food,Hussain Fakhari,9920095852,hussain_fakhari@yahoo.co.in,1 - 10 lacs,0,0,Products/5c051a388c023b6bd08aefb4a17989ea.jpg,2018-04-12,NaN,NaN,0
28,26,30477786,0,ALISTER EQUIPMENTS,MULLA SHABBIR FAKHRUDDIN MASTER,9823378666,sfmaster786@gmail.com,1 Cr - 25 Cr,0,0,Products/a381eb84df006a4a4ecb3ee538d5a9bb.pdf,2018-04-11,NaN,NaN,0
29,16,30494986,0,Vestige marketing,Huseina,7718029056,huseinabdalal@yahoo.co.in,1 - 10 lacs,0,0,Products/d55d97722bc0ad2e24ac07890ab3d3a5.jpg,2018-04-11,NaN,NaN,0
30,54,30495120,0,Little Honey,Taher Topiwala,006590178884,Tahertopi@gmail.com,10 lacs - 50 lacs,0,0,Products/29a56f210fef26aa9548f8257e162a84.png,2018-04-12,NaN,NaN,0
31,45,30802417,0,Muffadal Enterprise,Mohammed Gadyali,9666241995,Muffadalent@gmail.com,10 lacs - 50 lacs,0,0,Products/d541e70b225ce1ef01a148459e81a01a.pdf,2018-04-11,NaN,NaN,0
32,27,30909139,0,Raudat industries,Nisrin tailor,7357535288,nisrin.tara@gmail.com,1 - 10 lacs,0,0,Products/7453aab7bbff2293b2a77e8a467adaac.jpg,2018-04-11,NaN,NaN,0
33,19,30922537,0,Qasr Honey,Saleh and Mustafa Daginawala,0061411162892,qasrhoney@gmail.com,1 - 10 lacs,0,0,Products/e88d58688c1472b8e204c2fb638d77d0.jpg,2018-04-11,NaN,NaN,0
34,68,40401311,0,Shahi Raj,M Shabbir Abdulhusain Poonawala,7387095152,shabbir@abdeali.org,1 - 10 lacs,2781511,0,Products/00f7accd158564852d919e7e1847e361.jpg,2018-04-12,NaN,NaN,0
35,9,40454741,0,NaN,Abizer bhai Shabbirhusain bhai Madarwala,03366869257,abuzar_shabbir@hotmail.com,10 lacs - 50 lacs,0,0,Products/9f8f3c9b2e157bc895115d72e5117479.pdf,2018-04-06,16191.0,NaN,0
36,11,40459627,2909,NaN,Qasim,28189902342121231231231231231231231231231231,qasimshabbir@gmail.com,50 lacs - 1 Cr,0,0,Products/fca4b03a5b2a315f1feee4ec910a1f98.pdf,2018-04-06,4.0,NaN,0
37,67,40492326,0,Huzainskitchen,Zainab jamali,7066351446,Xainab52@gmail.com,1 - 10 lacs,0,0,Products/4f58d462a117e80cd1ce98c8ee5b22ec.jpg,2018-04-12,NaN,NaN,0
38,56,40497836,0,The little kitchen,Huzaifa mustafa,00923323591521,Lkco.khi@gmail.com,50 lacs - 1 Cr,0,0,Products/9abf7fa90e2bc04fafc7d5429eba0d00.jpg,2018-04-12,NaN,NaN,0
39,66,50426354,0,Choice corner,Juzer,7096115568,Ukanijuzer53@gmail.com,10 lacs - 50 lacs,0,0,Products/026d03627edb9744123c5306fbbbdf98.jpg,2018-04-12,NaN,NaN,0
40,25,50430949,0,ROYAL TAJMAHAL BEVERAGES,Husain Tajmahal,9909562552,husain.tajmahal128@gmail.com,50 lacs - 1 Cr,0,0,Products/db87381cb83d6a31f589f71f7885e01f.jpg,2018-04-11,NaN,NaN,0
41,50,50436202,0,Fiesta Bakers and Confectioners,Saifuddin Habibulla,9822059334,fiesta093@gmail.com,1 Cr - 25 Cr,0,0,Products/d838b9a95f754d74be545278bdcce14c.JPG,2018-04-11,NaN,NaN,0
42,43,50458658,0,World best health care product. Foreverliving ...,Mustafaa,8099707899,mus2212@gmail.com,100 Cr and Above,0,0,Products/0948eb3eaf134291699905b741f5cab4.pdf,2018-04-11,NaN,NaN,0
43,31,50462168,0,Roshan Pharma,Zakir Husain Kanchwala,7693976055,zakirkanchwala007@gmail.com,1 - 10 lacs,0,0,Products/3d9fa60c7127bccb5077464775a83cb1.jpg,2018-04-11,NaN,NaN,0
44,78,50476798,0,Vegetable supplier,Zoher abdeali siamwala,9374731392,Zohersiamwala1974@gmail @gmail.com,1 - 10 lacs,0,0,Products/c4643919a0cf842e1a1b45d8f8e315c9.jpg,2018-04-12,NaN,NaN,0
45,13,50494975,0,Al fakhri trading,Fatema nanabhai,254722604267,msfbj21@hotmail.com,1 - 10 lacs,0,0,Products/bad15c9d4aabad65e232a57844e196cc.jpg,2018-04-11,NaN,NaN,0
46,58,60408532,0,Vestige,Batul Aziz Vania,7383931934,batulvania36@gmail.com,1 - 10 lacs,0,0,Products/9b1cc173bae7954669102dc244955949.jpg,2018-04-12,NaN,NaN,0
47,30,60419607,0,CHEM IMPEX,Anis Patel,9408041433,mktg.chemimpex@gmail.com,1 Cr - 25 Cr,0,1071703126,Products/5d527bdf5546988cfc32eb7a57d6a363.pdf,2018-04-11,NaN,NaN,0
48,46,60445477,0,Pakeezah Paan Mouth-freshener,Husain,9490692461,mca.husain@gmail.com,1 - 10 lacs,0,0,Products/5bd0d25cbdda7c6a85ca097546afcb5f.jpg,2018-04-11,NaN,NaN,0
49,80,60464992,0,Taheri Traders,Taher Saifi,7725805253,saifitaher@gmail.com,1 - 10 lacs,0,0,Products/1f46f472f6c6fbfa512a368cec70eff6.JPG,2018-04-12,NaN,NaN,0

In [57]:
data[['its_number','contact_name','annual_turnover']][data.annual_turnover.str.startswith('10')]

    its_number                                 contact_name    annual_turnover
5     20397478  Mulla Shabbir bhai Shaikh Hasan bhai Bhatia  10 lacs - 50 lacs
13    30314735                                      Murtaza  10 lacs - 50 lacs
19    30390067                      Abdulkadir Khandalawala  10 lacs - 50 lacs
30    30495120                               Taher Topiwala  10 lacs - 50 lacs
31    30802417                            Mohammed Gadyali   10 lacs - 50 lacs
35    40454741    Abizer bhai  Shabbirhusain bhai Madarwala  10 lacs - 50 lacs
39    50426354                                        Juzer  10 lacs - 50 lacs
42    50458658                                     Mustafaa   100 Cr and Above

In [70]:
data[data.contact_name.str.endswith('ali')]

,id,its_number,business_id,business_name,contact_name,phone_no,email_id,annual_turnover,gstn_no,fssai_no,brouchers,created_at,created_by,updated_by,is_deleted
3,82,20352092,0,Taherabad enterprises,Abbas Jamali,9558161452,qutubpalace@gmail.com,1 - 10 lacs,0,0,Products/4928866c8c2cee3c1b2bbf97756c7027.JPG,2018-04-12,NaN,NaN,0
37,67,40492326,0,Huzainskitchen,Zainab jamali,7066351446,Xainab52@gmail.com,1 - 10 lacs,0,0,Products/4f58d462a117e80cd1ce98c8ee5b22ec.jpg,2018-04-12,NaN,NaN,0

In [78]:
import numpy as np
persons = pd.DataFrame({
    'name': ['Shahzad', 'Taha', 'Fatima', 'Khani', 'Samia'],
    'age': np.random.randint(1,40, size=[5]),#[20, 22, 21,21, 3]
    'percent': np.random.randint(40,95, size=[5])
})

In [79]:
persons

      name  age  percent
0  Shahzad   22       81
1     Taha    4       67
2   Fatima   22       40
3    Khani   10       63
4    Samia   33       42

In [80]:
def adult(age):
    if age < 18:
        return 'Child'
    return 'Adult'

In [81]:
persons['status'] = persons['age'].apply(adult)

In [82]:
persons

      name  age  percent status
0  Shahzad   22       81  Adult
1     Taha    4       67  Child
2   Fatima   22       40  Adult
3    Khani   10       63  Child
4    Samia   33       42  Adult

In [77]:
def grade(per):
    if(per < 60):
        return 'F'
    elif(per < 70):
        return 'C'
    elif(per < 80):
        return 'B'
    elif(per < 90):
        return 'A'
    return 'A+'

In [83]:
persons['grade'] = persons['percent'].apply(grade)
persons

      name  age  percent status grade
0  Shahzad   22       81  Adult     A
1     Taha    4       67  Child     C
2   Fatima   22       40  Adult     F
3    Khani   10       63  Child     C
4    Samia   33       42  Adult     F